# workmux project configuration
# Parallel Claude agents with git worktrees

#-------------------------------------------------------------------------------
# Git
#-------------------------------------------------------------------------------
main_branch: main
merge_strategy: squash

#-------------------------------------------------------------------------------
# Tmux
#-------------------------------------------------------------------------------
panes:
  - command: claude --dangerously-skip-permissions
    focus: true
  - split: horizontal
    size: 30

status_format: true
status_icons:
  working: "🤖"
  waiting: "💬"
  done: "✅"

#-------------------------------------------------------------------------------
# Agent
#-------------------------------------------------------------------------------
agent: claude

#-------------------------------------------------------------------------------
# Hooks
#-------------------------------------------------------------------------------
# post_create disabled - first task creates package.json
# post_create:
#   - pnpm install --silent

pre_merge:
  - pnpm type-check || true

post_merge:
  # Update PRD task status after successful merge
  - |
    if [[ -f .claude/.current-prd ]]; then
      PRD_NAME=$(cat .claude/.current-prd)
      TASK_NAME=$(git log -1 --pretty=%s | sed 's/Squashed commit.*//' | head -1)
      BRANCH_NAME="${WORKMUX_BRANCH:-unknown}"
      .claude/skills/PRD/scripts/update-task-status.sh "$PRD_NAME" "$BRANCH_NAME" completed 2>/dev/null || true
    fi

#-------------------------------------------------------------------------------
# Files
#-------------------------------------------------------------------------------
files:
  symlink:
    - node_modules

#-------------------------------------------------------------------------------
# Dashboard
#-------------------------------------------------------------------------------
dashboard:
  commit: "/commit"
  merge: "!workmux merge"
  preview_size: 60
