# workmux project configuration
# Parallel Claude agents with git worktrees

#-------------------------------------------------------------------------------
# Git
#-------------------------------------------------------------------------------
main_branch: main
merge_strategy: squash

#-------------------------------------------------------------------------------
# Tmux
#-------------------------------------------------------------------------------
panes:
  - command: claude --dangerously-skip-permissions
    focus: true
  - split: horizontal
    size: 30

status_format: true
status_icons:
  working: "🤖"
  waiting: "💬"
  done: "✅"

#-------------------------------------------------------------------------------
# Agent
#-------------------------------------------------------------------------------
agent: claude

#-------------------------------------------------------------------------------
# Hooks
#-------------------------------------------------------------------------------
# post_create disabled - first task creates package.json
# post_create:
#   - pnpm install --silent

pre_merge:
  - pnpm type-check || true

#-------------------------------------------------------------------------------
# Files
#-------------------------------------------------------------------------------
files:
  symlink:
    - node_modules

#-------------------------------------------------------------------------------
# Dashboard
#-------------------------------------------------------------------------------
dashboard:
  commit: "/commit"
  merge: "!workmux merge"
  preview_size: 60
